# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1080, 542)
        self.label_top = QtWidgets.QLabel(Form)
        self.label_top.setGeometry(QtCore.QRect(10, 10, 1071, 16))
        self.label_top.setStyleSheet("background-color: rgb(34, 194, 255);")
        self.label_top.setAlignment(QtCore.Qt.AlignCenter)
        self.label_top.setObjectName("label_top")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 30, 1071, 501))
        self.tabWidget.setStyleSheet("background-color: rgb(228, 255, 248);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButtonOpenPort = QtWidgets.QPushButton(self.tab)
        self.pushButtonOpenPort.setGeometry(QtCore.QRect(10, 10, 91, 23))
        self.pushButtonOpenPort.setObjectName("pushButtonOpenPort")
        self.pushButtonClosePort = QtWidgets.QPushButton(self.tab)
        self.pushButtonClosePort.setGeometry(QtCore.QRect(960, 10, 91, 23))
        self.pushButtonClosePort.setObjectName("pushButtonClosePort")
        self.checkBoxPLC = QtWidgets.QCheckBox(self.tab)
        self.checkBoxPLC.setGeometry(QtCore.QRect(120, 10, 51, 20))
        self.checkBoxPLC.setChecked(True)
        self.checkBoxPLC.setObjectName("checkBoxPLC")
        self.groupBoxAxisSpeed = QtWidgets.QGroupBox(self.tab)
        self.groupBoxAxisSpeed.setGeometry(QtCore.QRect(10, 40, 471, 161))
        self.groupBoxAxisSpeed.setObjectName("groupBoxAxisSpeed")
        self.label_5 = QtWidgets.QLabel(self.groupBoxAxisSpeed)
        self.label_5.setGeometry(QtCore.QRect(10, 130, 67, 17))
        self.label_5.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_5.setObjectName("label_5")
        self.pushButtonSpeedSet = QtWidgets.QPushButton(self.groupBoxAxisSpeed)
        self.pushButtonSpeedSet.setGeometry(QtCore.QRect(243, 74, 89, 31))
        self.pushButtonSpeedSet.setObjectName("pushButtonSpeedSet")
        self.label_3 = QtWidgets.QLabel(self.groupBoxAxisSpeed)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 67, 17))
        self.label_3.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_3.setObjectName("label_3")
        self.textEditXSpeedSet = QtWidgets.QTextEdit(self.groupBoxAxisSpeed)
        self.textEditXSpeedSet.setGeometry(QtCore.QRect(110, 23, 91, 31))
        self.textEditXSpeedSet.setObjectName("textEditXSpeedSet")
        self.pushButtonSpeedGet = QtWidgets.QPushButton(self.groupBoxAxisSpeed)
        self.pushButtonSpeedGet.setGeometry(QtCore.QRect(353, 74, 89, 31))
        self.pushButtonSpeedGet.setObjectName("pushButtonSpeedGet")
        self.label = QtWidgets.QLabel(self.groupBoxAxisSpeed)
        self.label.setGeometry(QtCore.QRect(10, 30, 67, 17))
        self.label.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label.setObjectName("label")
        self.textEditZSpeedSet = QtWidgets.QTextEdit(self.groupBoxAxisSpeed)
        self.textEditZSpeedSet.setGeometry(QtCore.QRect(110, 123, 91, 31))
        self.textEditZSpeedSet.setObjectName("textEditZSpeedSet")
        self.textEditYSpeedSet = QtWidgets.QTextEdit(self.groupBoxAxisSpeed)
        self.textEditYSpeedSet.setGeometry(QtCore.QRect(110, 73, 91, 31))
        self.textEditYSpeedSet.setObjectName("textEditYSpeedSet")
        self.groupBoxAxisLimit = QtWidgets.QGroupBox(self.tab)
        self.groupBoxAxisLimit.setGeometry(QtCore.QRect(500, 40, 591, 161))
        self.groupBoxAxisLimit.setObjectName("groupBoxAxisLimit")
        self.pushButtonLimitGet = QtWidgets.QPushButton(self.groupBoxAxisLimit)
        self.pushButtonLimitGet.setGeometry(QtCore.QRect(470, 105, 81, 31))
        self.pushButtonLimitGet.setObjectName("pushButtonLimitGet")
        self.label_20 = QtWidgets.QLabel(self.groupBoxAxisLimit)
        self.label_20.setGeometry(QtCore.QRect(86, 26, 251, 141))
        self.label_20.setStyleSheet("background-color: rgb(255, 249, 189);")
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.pushButtonLimitSet = QtWidgets.QPushButton(self.groupBoxAxisLimit)
        self.pushButtonLimitSet.setGeometry(QtCore.QRect(360, 105, 81, 31))
        self.pushButtonLimitSet.setObjectName("pushButtonLimitSet")
        self.label_2 = QtWidgets.QLabel(self.groupBoxAxisLimit)
        self.label_2.setGeometry(QtCore.QRect(10, 36, 67, 17))
        self.label_2.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_2.setObjectName("label_2")
        self.label_8 = QtWidgets.QLabel(self.groupBoxAxisLimit)
        self.label_8.setGeometry(QtCore.QRect(10, 136, 67, 17))
        self.label_8.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_8.setObjectName("label_8")
        self.label_4 = QtWidgets.QLabel(self.groupBoxAxisLimit)
        self.label_4.setGeometry(QtCore.QRect(10, 86, 67, 17))
        self.label_4.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_4.setObjectName("label_4")
        self.label_maxlimit = QtWidgets.QLabel(self.groupBoxAxisLimit)
        self.label_maxlimit.setGeometry(QtCore.QRect(120, 10, 54, 20))
        self.label_maxlimit.setStyleSheet("background-color: rgb(58, 255, 13);")
        self.label_maxlimit.setObjectName("label_maxlimit")
        self.label_minlimit = QtWidgets.QLabel(self.groupBoxAxisLimit)
        self.label_minlimit.setGeometry(QtCore.QRect(243, 10, 54, 20))
        self.label_minlimit.setStyleSheet("background-color: rgb(58, 255, 13);")
        self.label_minlimit.setObjectName("label_minlimit")
        self.textEditPassword = QtWidgets.QTextEdit(self.groupBoxAxisLimit)
        self.textEditPassword.setGeometry(QtCore.QRect(360, 60, 81, 31))
        self.textEditPassword.setObjectName("textEditPassword")
        self.pushButtonPassword = QtWidgets.QPushButton(self.groupBoxAxisLimit)
        self.pushButtonPassword.setGeometry(QtCore.QRect(470, 60, 81, 31))
        self.pushButtonPassword.setStyleSheet("background-color: rgb(58, 255, 13);")
        self.pushButtonPassword.setObjectName("pushButtonPassword")
        self.textEditXMaxLimit = QtWidgets.QTextEdit(self.groupBoxAxisLimit)
        self.textEditXMaxLimit.setGeometry(QtCore.QRect(100, 36, 101, 21))
        self.textEditXMaxLimit.setObjectName("textEditXMaxLimit")
        self.textEditXMinLimit = QtWidgets.QTextEdit(self.groupBoxAxisLimit)
        self.textEditXMinLimit.setGeometry(QtCore.QRect(220, 35, 101, 21))
        self.textEditXMinLimit.setObjectName("textEditXMinLimit")
        self.textEditYMinLimit = QtWidgets.QTextEdit(self.groupBoxAxisLimit)
        self.textEditYMinLimit.setGeometry(QtCore.QRect(220, 82, 101, 21))
        self.textEditYMinLimit.setObjectName("textEditYMinLimit")
        self.textEditYMaxLimit = QtWidgets.QTextEdit(self.groupBoxAxisLimit)
        self.textEditYMaxLimit.setGeometry(QtCore.QRect(100, 83, 101, 21))
        self.textEditYMaxLimit.setObjectName("textEditYMaxLimit")
        self.textEditZMinLimit = QtWidgets.QTextEdit(self.groupBoxAxisLimit)
        self.textEditZMinLimit.setGeometry(QtCore.QRect(220, 134, 101, 21))
        self.textEditZMinLimit.setObjectName("textEditZMinLimit")
        self.textEditZMaxLimit = QtWidgets.QTextEdit(self.groupBoxAxisLimit)
        self.textEditZMaxLimit.setGeometry(QtCore.QRect(100, 135, 101, 21))
        self.textEditZMaxLimit.setObjectName("textEditZMaxLimit")
        self.label_20.raise_()
        self.pushButtonLimitGet.raise_()
        self.pushButtonLimitSet.raise_()
        self.label_2.raise_()
        self.label_8.raise_()
        self.label_4.raise_()
        self.label_maxlimit.raise_()
        self.label_minlimit.raise_()
        self.textEditPassword.raise_()
        self.pushButtonPassword.raise_()
        self.textEditXMaxLimit.raise_()
        self.textEditXMinLimit.raise_()
        self.textEditYMinLimit.raise_()
        self.textEditYMaxLimit.raise_()
        self.textEditZMinLimit.raise_()
        self.textEditZMaxLimit.raise_()
        self.groupBoxMoveCoordiante = QtWidgets.QGroupBox(self.tab)
        self.groupBoxMoveCoordiante.setGeometry(QtCore.QRect(10, 200, 471, 141))
        self.groupBoxMoveCoordiante.setObjectName("groupBoxMoveCoordiante")
        self.textEditxMove = QtWidgets.QTextEdit(self.groupBoxMoveCoordiante)
        self.textEditxMove.setGeometry(QtCore.QRect(110, 24, 91, 31))
        self.textEditxMove.setObjectName("textEditxMove")
        self.textEdityMove = QtWidgets.QTextEdit(self.groupBoxMoveCoordiante)
        self.textEdityMove.setGeometry(QtCore.QRect(110, 64, 91, 31))
        self.textEdityMove.setObjectName("textEdityMove")
        self.textEditzMove = QtWidgets.QTextEdit(self.groupBoxMoveCoordiante)
        self.textEditzMove.setGeometry(QtCore.QRect(110, 104, 91, 31))
        self.textEditzMove.setObjectName("textEditzMove")
        self.pushButtonMovex = QtWidgets.QPushButton(self.groupBoxMoveCoordiante)
        self.pushButtonMovex.setGeometry(QtCore.QRect(250, 30, 75, 19))
        self.pushButtonMovex.setObjectName("pushButtonMovex")
        self.pushButtonMovey = QtWidgets.QPushButton(self.groupBoxMoveCoordiante)
        self.pushButtonMovey.setGeometry(QtCore.QRect(250, 70, 75, 20))
        self.pushButtonMovey.setObjectName("pushButtonMovey")
        self.pushButtonMovez = QtWidgets.QPushButton(self.groupBoxMoveCoordiante)
        self.pushButtonMovez.setGeometry(QtCore.QRect(250, 110, 75, 19))
        self.pushButtonMovez.setObjectName("pushButtonMovez")
        self.pushButtonGetx = QtWidgets.QPushButton(self.groupBoxMoveCoordiante)
        self.pushButtonGetx.setGeometry(QtCore.QRect(350, 30, 75, 19))
        self.pushButtonGetx.setObjectName("pushButtonGetx")
        self.pushButtonGety = QtWidgets.QPushButton(self.groupBoxMoveCoordiante)
        self.pushButtonGety.setGeometry(QtCore.QRect(350, 70, 75, 19))
        self.pushButtonGety.setObjectName("pushButtonGety")
        self.pushButtonGetz = QtWidgets.QPushButton(self.groupBoxMoveCoordiante)
        self.pushButtonGetz.setGeometry(QtCore.QRect(350, 110, 75, 19))
        self.pushButtonGetz.setObjectName("pushButtonGetz")
        self.label_10 = QtWidgets.QLabel(self.groupBoxMoveCoordiante)
        self.label_10.setGeometry(QtCore.QRect(10, 30, 67, 17))
        self.label_10.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBoxMoveCoordiante)
        self.label_11.setGeometry(QtCore.QRect(10, 110, 67, 17))
        self.label_11.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_11.setObjectName("label_11")
        self.label_14 = QtWidgets.QLabel(self.groupBoxMoveCoordiante)
        self.label_14.setGeometry(QtCore.QRect(10, 70, 67, 17))
        self.label_14.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_14.setObjectName("label_14")
        self.groupBoxAxisStepMove = QtWidgets.QGroupBox(self.tab)
        self.groupBoxAxisStepMove.setGeometry(QtCore.QRect(500, 200, 341, 141))
        self.groupBoxAxisStepMove.setObjectName("groupBoxAxisStepMove")
        self.label_12 = QtWidgets.QLabel(self.groupBoxAxisStepMove)
        self.label_12.setGeometry(QtCore.QRect(10, 30, 67, 17))
        self.label_12.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_12.setObjectName("label_12")
        self.label_15 = QtWidgets.QLabel(self.groupBoxAxisStepMove)
        self.label_15.setGeometry(QtCore.QRect(10, 70, 67, 17))
        self.label_15.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBoxAxisStepMove)
        self.label_16.setGeometry(QtCore.QRect(10, 110, 67, 17))
        self.label_16.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_16.setObjectName("label_16")
        self.pushButtonStepMoveZ = QtWidgets.QPushButton(self.groupBoxAxisStepMove)
        self.pushButtonStepMoveZ.setGeometry(QtCore.QRect(230, 109, 75, 19))
        self.pushButtonStepMoveZ.setObjectName("pushButtonStepMoveZ")
        self.textEditStepMoveX = QtWidgets.QTextEdit(self.groupBoxAxisStepMove)
        self.textEditStepMoveX.setGeometry(QtCore.QRect(110, 24, 91, 31))
        self.textEditStepMoveX.setObjectName("textEditStepMoveX")
        self.textEditStepMoveZ = QtWidgets.QTextEdit(self.groupBoxAxisStepMove)
        self.textEditStepMoveZ.setGeometry(QtCore.QRect(110, 104, 91, 31))
        self.textEditStepMoveZ.setObjectName("textEditStepMoveZ")
        self.pushButtonStepMoveY = QtWidgets.QPushButton(self.groupBoxAxisStepMove)
        self.pushButtonStepMoveY.setGeometry(QtCore.QRect(230, 69, 75, 20))
        self.pushButtonStepMoveY.setObjectName("pushButtonStepMoveY")
        self.pushButtonStepMoveX = QtWidgets.QPushButton(self.groupBoxAxisStepMove)
        self.pushButtonStepMoveX.setGeometry(QtCore.QRect(230, 29, 75, 19))
        self.pushButtonStepMoveX.setObjectName("pushButtonStepMoveX")
        self.textEditStepMoveY = QtWidgets.QTextEdit(self.groupBoxAxisStepMove)
        self.textEditStepMoveY.setGeometry(QtCore.QRect(110, 64, 91, 31))
        self.textEditStepMoveY.setObjectName("textEditStepMoveY")
        self.pushButtonSignalReSet = QtWidgets.QPushButton(self.tab)
        self.pushButtonSignalReSet.setGeometry(QtCore.QRect(220, 10, 111, 23))
        self.pushButtonSignalReSet.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButtonSignalReSet.setObjectName("pushButtonSignalReSet")
        self.pushButtonGetPLCVer = QtWidgets.QPushButton(self.tab)
        self.pushButtonGetPLCVer.setGeometry(QtCore.QRect(380, 10, 111, 23))
        self.pushButtonGetPLCVer.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButtonGetPLCVer.setObjectName("pushButtonGetPLCVer")
        self.textEditPLCVer = QtWidgets.QTextEdit(self.tab)
        self.textEditPLCVer.setGeometry(QtCore.QRect(510, 10, 104, 21))
        self.textEditPLCVer.setObjectName("textEditPLCVer")
        self.pushButtonCylinderIn = QtWidgets.QPushButton(self.tab)
        self.pushButtonCylinderIn.setGeometry(QtCore.QRect(40, 370, 101, 21))
        self.pushButtonCylinderIn.setObjectName("pushButtonCylinderIn")
        self.pushButtonCylinderOut = QtWidgets.QPushButton(self.tab)
        self.pushButtonCylinderOut.setGeometry(QtCore.QRect(40, 410, 101, 21))
        self.pushButtonCylinderOut.setObjectName("pushButtonCylinderOut")
        self.pushButtonPin1Down = QtWidgets.QPushButton(self.tab)
        self.pushButtonPin1Down.setGeometry(QtCore.QRect(180, 370, 101, 21))
        self.pushButtonPin1Down.setObjectName("pushButtonPin1Down")
        self.pushButtonPin1Up = QtWidgets.QPushButton(self.tab)
        self.pushButtonPin1Up.setGeometry(QtCore.QRect(180, 410, 101, 21))
        self.pushButtonPin1Up.setObjectName("pushButtonPin1Up")
        self.pushButtonPin2Up = QtWidgets.QPushButton(self.tab)
        self.pushButtonPin2Up.setGeometry(QtCore.QRect(330, 410, 101, 21))
        self.pushButtonPin2Up.setObjectName("pushButtonPin2Up")
        self.pushButtonPin2Down = QtWidgets.QPushButton(self.tab)
        self.pushButtonPin2Down.setGeometry(QtCore.QRect(330, 370, 101, 21))
        self.pushButtonPin2Down.setObjectName("pushButtonPin2Down")
        self.pushButtonUSBIn = QtWidgets.QPushButton(self.tab)
        self.pushButtonUSBIn.setGeometry(QtCore.QRect(610, 370, 101, 21))
        self.pushButtonUSBIn.setObjectName("pushButtonUSBIn")
        self.pushButtonUSBOut = QtWidgets.QPushButton(self.tab)
        self.pushButtonUSBOut.setGeometry(QtCore.QRect(610, 410, 101, 21))
        self.pushButtonUSBOut.setObjectName("pushButtonUSBOut")
        self.pushButtonCloseCurtain = QtWidgets.QPushButton(self.tab)
        self.pushButtonCloseCurtain.setGeometry(QtCore.QRect(470, 370, 101, 21))
        self.pushButtonCloseCurtain.setObjectName("pushButtonCloseCurtain")
        self.pushButtonOpenCurtain = QtWidgets.QPushButton(self.tab)
        self.pushButtonOpenCurtain.setGeometry(QtCore.QRect(470, 410, 101, 21))
        self.pushButtonOpenCurtain.setObjectName("pushButtonOpenCurtain")
        self.textEditBurnTimes = QtWidgets.QTextEdit(self.tab)
        self.textEditBurnTimes.setGeometry(QtCore.QRect(910, 230, 91, 31))
        self.textEditBurnTimes.setObjectName("textEditBurnTimes")
        self.pushButtonBurn = QtWidgets.QPushButton(self.tab)
        self.pushButtonBurn.setGeometry(QtCore.QRect(870, 280, 171, 21))
        self.pushButtonBurn.setObjectName("pushButtonBurn")
        self.pushButtonDCIn = QtWidgets.QPushButton(self.tab)
        self.pushButtonDCIn.setGeometry(QtCore.QRect(750, 370, 101, 21))
        self.pushButtonDCIn.setObjectName("pushButtonDCIn")
        self.pushButtonDCOut = QtWidgets.QPushButton(self.tab)
        self.pushButtonDCOut.setGeometry(QtCore.QRect(750, 410, 101, 21))
        self.pushButtonDCOut.setObjectName("pushButtonDCOut")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(210, 110, 181, 131))
        self.label_6.setStyleSheet("background-color: rgb(255, 255, 221);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.pushButtonUp = QtWidgets.QPushButton(self.tab_2)
        self.pushButtonUp.setGeometry(QtCore.QRect(250, 50, 113, 32))
        self.pushButtonUp.setStyleSheet("background-color: rgb(253, 162, 218);")
        self.pushButtonUp.setObjectName("pushButtonUp")
        self.pushButtonDown = QtWidgets.QPushButton(self.tab_2)
        self.pushButtonDown.setGeometry(QtCore.QRect(250, 280, 113, 32))
        self.pushButtonDown.setStyleSheet("background-color: rgb(124, 255, 210);")
        self.pushButtonDown.setObjectName("pushButtonDown")
        self.pushButtonRight = QtWidgets.QPushButton(self.tab_2)
        self.pushButtonRight.setGeometry(QtCore.QRect(440, 160, 113, 32))
        self.pushButtonRight.setStyleSheet("background-color: rgb(158, 255, 150);")
        self.pushButtonRight.setObjectName("pushButtonRight")
        self.pushButtonLeft = QtWidgets.QPushButton(self.tab_2)
        self.pushButtonLeft.setGeometry(QtCore.QRect(50, 160, 113, 32))
        self.pushButtonLeft.setStyleSheet("background-color: rgb(155, 255, 148);")
        self.pushButtonLeft.setObjectName("pushButtonLeft")
        self.pushButtonMiddle = QtWidgets.QPushButton(self.tab_2)
        self.pushButtonMiddle.setGeometry(QtCore.QRect(250, 200, 113, 32))
        self.pushButtonMiddle.setStyleSheet("background-color: rgb(179, 141, 255);")
        self.pushButtonMiddle.setObjectName("pushButtonMiddle")
        self.pushButtonStartCal = QtWidgets.QPushButton(self.tab_2)
        self.pushButtonStartCal.setGeometry(QtCore.QRect(660, 160, 151, 81))
        self.pushButtonStartCal.setStyleSheet("background-color: rgb(158, 255, 150);")
        self.pushButtonStartCal.setObjectName("pushButtonStartCal")
        self.tabWidget.addTab(self.tab_2, "")
        self.label_bottom = QtWidgets.QLabel(Form)
        self.label_bottom.setGeometry(QtCore.QRect(10, 520, 1071, 20))
        self.label_bottom.setStyleSheet("background-color: rgb(34, 194, 255);")
        self.label_bottom.setAlignment(QtCore.Qt.AlignCenter)
        self.label_bottom.setObjectName("label_bottom")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "BojayE71Touch"))
        self.label_top.setText(_translate("Form", "Bojay P71Touch UI V1.0"))
        self.pushButtonOpenPort.setText(_translate("Form", "OpenPort"))
        self.pushButtonClosePort.setText(_translate("Form", "ClosePort"))
        self.checkBoxPLC.setText(_translate("Form", "PLC"))
        self.groupBoxAxisSpeed.setTitle(_translate("Form", "Axis Speed"))
        self.label_5.setText(_translate("Form", "Z Axis"))
        self.pushButtonSpeedSet.setText(_translate("Form", "Set"))
        self.label_3.setText(_translate("Form", "Y Axis"))
        self.pushButtonSpeedGet.setText(_translate("Form", "Get"))
        self.label.setText(_translate("Form", "X Axis"))
        self.groupBoxAxisLimit.setTitle(_translate("Form", "Axis Limit"))
        self.pushButtonLimitGet.setText(_translate("Form", "Get"))
        self.pushButtonLimitSet.setText(_translate("Form", "Set"))
        self.label_2.setText(_translate("Form", "X Axis"))
        self.label_8.setText(_translate("Form", "Z Axis"))
        self.label_4.setText(_translate("Form", "Y Axis"))
        self.label_maxlimit.setText(_translate("Form", "MaxLimit"))
        self.label_minlimit.setText(_translate("Form", "MinLimit"))
        self.pushButtonPassword.setText(_translate("Form", "Password"))
        self.groupBoxMoveCoordiante.setTitle(_translate("Form", "Move Coordinate"))
        self.pushButtonMovex.setText(_translate("Form", "Move X"))
        self.pushButtonMovey.setText(_translate("Form", "Move Y"))
        self.pushButtonMovez.setText(_translate("Form", "Move Z"))
        self.pushButtonGetx.setText(_translate("Form", "Get X"))
        self.pushButtonGety.setText(_translate("Form", "Get Y"))
        self.pushButtonGetz.setText(_translate("Form", "Get Z"))
        self.label_10.setText(_translate("Form", "X Axis"))
        self.label_11.setText(_translate("Form", "Z Axis"))
        self.label_14.setText(_translate("Form", "Y Axis"))
        self.groupBoxAxisStepMove.setTitle(_translate("Form", "Set step"))
        self.label_12.setText(_translate("Form", "X Axis"))
        self.label_15.setText(_translate("Form", "Y Axis"))
        self.label_16.setText(_translate("Form", "Z Axis"))
        self.pushButtonStepMoveZ.setText(_translate("Form", "Move Z"))
        self.pushButtonStepMoveY.setText(_translate("Form", "Move Y"))
        self.pushButtonStepMoveX.setText(_translate("Form", "Move X"))
        self.pushButtonSignalReSet.setText(_translate("Form", "SignalReSet"))
        self.pushButtonGetPLCVer.setText(_translate("Form", "ReadPCLVer"))
        self.pushButtonCylinderIn.setText(_translate("Form", "气缸进"))
        self.pushButtonCylinderOut.setText(_translate("Form", "气缸出"))
        self.pushButtonPin1Down.setText(_translate("Form", "Pin1下降"))
        self.pushButtonPin1Up.setText(_translate("Form", "Pin1上升"))
        self.pushButtonPin2Up.setText(_translate("Form", "Pin2上升"))
        self.pushButtonPin2Down.setText(_translate("Form", "Pin2下降"))
        self.pushButtonUSBIn.setText(_translate("Form", "USB进"))
        self.pushButtonUSBOut.setText(_translate("Form", "USB出"))
        self.pushButtonCloseCurtain.setText(_translate("Form", "关闭光栅"))
        self.pushButtonOpenCurtain.setText(_translate("Form", "打开光栅"))
        self.pushButtonBurn.setText(_translate("Form", "开始老化"))
        self.pushButtonDCIn.setText(_translate("Form", "DC进"))
        self.pushButtonDCOut.setText(_translate("Form", "DC出"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "PLC"))
        self.label_6.setText(_translate("Form", "Cal Kit"))
        self.pushButtonUp.setText(_translate("Form", "Set UP"))
        self.pushButtonDown.setText(_translate("Form", "Set Down"))
        self.pushButtonRight.setText(_translate("Form", "Set Right"))
        self.pushButtonLeft.setText(_translate("Form", "Set Left"))
        self.pushButtonMiddle.setText(_translate("Form", "Set Middle"))
        self.pushButtonStartCal.setText(_translate("Form", "Start Cal"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Cal"))
        self.label_bottom.setText(_translate("Form", "Developed by Bojay"))

