# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1084, 566)
        self.label_top = QtWidgets.QLabel(Form)
        self.label_top.setGeometry(QtCore.QRect(10, 10, 1071, 16))
        self.label_top.setStyleSheet("background-color: rgb(34, 194, 255);")
        self.label_top.setAlignment(QtCore.Qt.AlignCenter)
        self.label_top.setObjectName("label_top")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 30, 1071, 501))
        self.tabWidget.setStyleSheet("background-color: rgb(228, 255, 248);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButtonOpenPort = QtWidgets.QPushButton(self.tab)
        self.pushButtonOpenPort.setGeometry(QtCore.QRect(10, 10, 91, 23))
        self.pushButtonOpenPort.setObjectName("pushButtonOpenPort")
        self.pushButtonClosePort = QtWidgets.QPushButton(self.tab)
        self.pushButtonClosePort.setGeometry(QtCore.QRect(960, 10, 91, 23))
        self.pushButtonClosePort.setObjectName("pushButtonClosePort")
        self.checkBoxPLC = QtWidgets.QCheckBox(self.tab)
        self.checkBoxPLC.setGeometry(QtCore.QRect(120, 10, 51, 20))
        self.checkBoxPLC.setChecked(True)
        self.checkBoxPLC.setObjectName("checkBoxPLC")
        self.groupBoxAxisSpeed = QtWidgets.QGroupBox(self.tab)
        self.groupBoxAxisSpeed.setGeometry(QtCore.QRect(10, 40, 471, 161))
        self.groupBoxAxisSpeed.setObjectName("groupBoxAxisSpeed")
        self.label_5 = QtWidgets.QLabel(self.groupBoxAxisSpeed)
        self.label_5.setGeometry(QtCore.QRect(10, 130, 67, 17))
        self.label_5.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_5.setObjectName("label_5")
        self.pushButtonSpeedSet = QtWidgets.QPushButton(self.groupBoxAxisSpeed)
        self.pushButtonSpeedSet.setGeometry(QtCore.QRect(243, 74, 89, 31))
        self.pushButtonSpeedSet.setObjectName("pushButtonSpeedSet")
        self.label_3 = QtWidgets.QLabel(self.groupBoxAxisSpeed)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 67, 17))
        self.label_3.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_3.setObjectName("label_3")
        self.textEditXSpeedSet = QtWidgets.QTextEdit(self.groupBoxAxisSpeed)
        self.textEditXSpeedSet.setGeometry(QtCore.QRect(110, 23, 91, 31))
        self.textEditXSpeedSet.setObjectName("textEditXSpeedSet")
        self.pushButtonSpeedGet = QtWidgets.QPushButton(self.groupBoxAxisSpeed)
        self.pushButtonSpeedGet.setGeometry(QtCore.QRect(353, 74, 89, 31))
        self.pushButtonSpeedGet.setObjectName("pushButtonSpeedGet")
        self.label = QtWidgets.QLabel(self.groupBoxAxisSpeed)
        self.label.setGeometry(QtCore.QRect(10, 30, 67, 17))
        self.label.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label.setObjectName("label")
        self.textEditZSpeedSet = QtWidgets.QTextEdit(self.groupBoxAxisSpeed)
        self.textEditZSpeedSet.setGeometry(QtCore.QRect(110, 123, 91, 31))
        self.textEditZSpeedSet.setObjectName("textEditZSpeedSet")
        self.textEditYSpeedSet = QtWidgets.QTextEdit(self.groupBoxAxisSpeed)
        self.textEditYSpeedSet.setGeometry(QtCore.QRect(110, 73, 91, 31))
        self.textEditYSpeedSet.setObjectName("textEditYSpeedSet")
        self.groupBoxAxisLimit = QtWidgets.QGroupBox(self.tab)
        self.groupBoxAxisLimit.setGeometry(QtCore.QRect(500, 40, 591, 161))
        self.groupBoxAxisLimit.setObjectName("groupBoxAxisLimit")
        self.pushButtonLimitGet = QtWidgets.QPushButton(self.groupBoxAxisLimit)
        self.pushButtonLimitGet.setGeometry(QtCore.QRect(470, 105, 81, 31))
        self.pushButtonLimitGet.setObjectName("pushButtonLimitGet")
        self.label_20 = QtWidgets.QLabel(self.groupBoxAxisLimit)
        self.label_20.setGeometry(QtCore.QRect(86, 26, 251, 141))
        self.label_20.setStyleSheet("background-color: rgb(255, 249, 189);")
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.pushButtonLimitSet = QtWidgets.QPushButton(self.groupBoxAxisLimit)
        self.pushButtonLimitSet.setGeometry(QtCore.QRect(360, 105, 81, 31))
        self.pushButtonLimitSet.setObjectName("pushButtonLimitSet")
        self.label_2 = QtWidgets.QLabel(self.groupBoxAxisLimit)
        self.label_2.setGeometry(QtCore.QRect(10, 36, 67, 17))
        self.label_2.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_2.setObjectName("label_2")
        self.label_8 = QtWidgets.QLabel(self.groupBoxAxisLimit)
        self.label_8.setGeometry(QtCore.QRect(10, 136, 67, 17))
        self.label_8.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_8.setObjectName("label_8")
        self.label_4 = QtWidgets.QLabel(self.groupBoxAxisLimit)
        self.label_4.setGeometry(QtCore.QRect(10, 86, 67, 17))
        self.label_4.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_4.setObjectName("label_4")
        self.label_maxlimit = QtWidgets.QLabel(self.groupBoxAxisLimit)
        self.label_maxlimit.setGeometry(QtCore.QRect(120, 10, 54, 20))
        self.label_maxlimit.setStyleSheet("background-color: rgb(58, 255, 13);")
        self.label_maxlimit.setObjectName("label_maxlimit")
        self.label_minlimit = QtWidgets.QLabel(self.groupBoxAxisLimit)
        self.label_minlimit.setGeometry(QtCore.QRect(243, 10, 54, 20))
        self.label_minlimit.setStyleSheet("background-color: rgb(58, 255, 13);")
        self.label_minlimit.setObjectName("label_minlimit")
        self.textEditPassword = QtWidgets.QTextEdit(self.groupBoxAxisLimit)
        self.textEditPassword.setGeometry(QtCore.QRect(360, 60, 81, 31))
        self.textEditPassword.setObjectName("textEditPassword")
        self.pushButtonPassword = QtWidgets.QPushButton(self.groupBoxAxisLimit)
        self.pushButtonPassword.setGeometry(QtCore.QRect(470, 60, 81, 31))
        self.pushButtonPassword.setStyleSheet("background-color: rgb(58, 255, 13);")
        self.pushButtonPassword.setObjectName("pushButtonPassword")
        self.textEditXMaxLimit = QtWidgets.QTextEdit(self.groupBoxAxisLimit)
        self.textEditXMaxLimit.setGeometry(QtCore.QRect(100, 36, 101, 21))
        self.textEditXMaxLimit.setObjectName("textEditXMaxLimit")
        self.textEditXMinLimit = QtWidgets.QTextEdit(self.groupBoxAxisLimit)
        self.textEditXMinLimit.setGeometry(QtCore.QRect(220, 35, 101, 21))
        self.textEditXMinLimit.setObjectName("textEditXMinLimit")
        self.textEditYMinLimit = QtWidgets.QTextEdit(self.groupBoxAxisLimit)
        self.textEditYMinLimit.setGeometry(QtCore.QRect(220, 82, 101, 21))
        self.textEditYMinLimit.setObjectName("textEditYMinLimit")
        self.textEditYMaxLimit = QtWidgets.QTextEdit(self.groupBoxAxisLimit)
        self.textEditYMaxLimit.setGeometry(QtCore.QRect(100, 83, 101, 21))
        self.textEditYMaxLimit.setObjectName("textEditYMaxLimit")
        self.textEditZMinLimit = QtWidgets.QTextEdit(self.groupBoxAxisLimit)
        self.textEditZMinLimit.setGeometry(QtCore.QRect(220, 134, 101, 21))
        self.textEditZMinLimit.setObjectName("textEditZMinLimit")
        self.textEditZMaxLimit = QtWidgets.QTextEdit(self.groupBoxAxisLimit)
        self.textEditZMaxLimit.setGeometry(QtCore.QRect(100, 135, 101, 21))
        self.textEditZMaxLimit.setObjectName("textEditZMaxLimit")
        self.label_20.raise_()
        self.pushButtonLimitGet.raise_()
        self.pushButtonLimitSet.raise_()
        self.label_2.raise_()
        self.label_8.raise_()
        self.label_4.raise_()
        self.label_maxlimit.raise_()
        self.label_minlimit.raise_()
        self.textEditPassword.raise_()
        self.pushButtonPassword.raise_()
        self.textEditXMaxLimit.raise_()
        self.textEditXMinLimit.raise_()
        self.textEditYMinLimit.raise_()
        self.textEditYMaxLimit.raise_()
        self.textEditZMinLimit.raise_()
        self.textEditZMaxLimit.raise_()
        self.groupBoxMoveCoordiante = QtWidgets.QGroupBox(self.tab)
        self.groupBoxMoveCoordiante.setGeometry(QtCore.QRect(10, 200, 471, 141))
        self.groupBoxMoveCoordiante.setObjectName("groupBoxMoveCoordiante")
        self.textEditxMove = QtWidgets.QTextEdit(self.groupBoxMoveCoordiante)
        self.textEditxMove.setGeometry(QtCore.QRect(110, 24, 91, 31))
        self.textEditxMove.setObjectName("textEditxMove")
        self.textEdityMove = QtWidgets.QTextEdit(self.groupBoxMoveCoordiante)
        self.textEdityMove.setGeometry(QtCore.QRect(110, 64, 91, 31))
        self.textEdityMove.setObjectName("textEdityMove")
        self.textEditzMove = QtWidgets.QTextEdit(self.groupBoxMoveCoordiante)
        self.textEditzMove.setGeometry(QtCore.QRect(110, 104, 91, 31))
        self.textEditzMove.setObjectName("textEditzMove")
        self.pushButtonMovex = QtWidgets.QPushButton(self.groupBoxMoveCoordiante)
        self.pushButtonMovex.setGeometry(QtCore.QRect(250, 30, 75, 19))
        self.pushButtonMovex.setObjectName("pushButtonMovex")
        self.pushButtonMovey = QtWidgets.QPushButton(self.groupBoxMoveCoordiante)
        self.pushButtonMovey.setGeometry(QtCore.QRect(250, 70, 75, 20))
        self.pushButtonMovey.setObjectName("pushButtonMovey")
        self.pushButtonMovez = QtWidgets.QPushButton(self.groupBoxMoveCoordiante)
        self.pushButtonMovez.setGeometry(QtCore.QRect(250, 110, 75, 19))
        self.pushButtonMovez.setObjectName("pushButtonMovez")
        self.pushButtonGetx = QtWidgets.QPushButton(self.groupBoxMoveCoordiante)
        self.pushButtonGetx.setGeometry(QtCore.QRect(350, 30, 75, 19))
        self.pushButtonGetx.setObjectName("pushButtonGetx")
        self.pushButtonGety = QtWidgets.QPushButton(self.groupBoxMoveCoordiante)
        self.pushButtonGety.setGeometry(QtCore.QRect(350, 70, 75, 19))
        self.pushButtonGety.setObjectName("pushButtonGety")
        self.pushButtonGetz = QtWidgets.QPushButton(self.groupBoxMoveCoordiante)
        self.pushButtonGetz.setGeometry(QtCore.QRect(350, 110, 75, 19))
        self.pushButtonGetz.setObjectName("pushButtonGetz")
        self.label_10 = QtWidgets.QLabel(self.groupBoxMoveCoordiante)
        self.label_10.setGeometry(QtCore.QRect(10, 30, 67, 17))
        self.label_10.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBoxMoveCoordiante)
        self.label_11.setGeometry(QtCore.QRect(10, 110, 67, 17))
        self.label_11.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_11.setObjectName("label_11")
        self.label_14 = QtWidgets.QLabel(self.groupBoxMoveCoordiante)
        self.label_14.setGeometry(QtCore.QRect(10, 70, 67, 17))
        self.label_14.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_14.setObjectName("label_14")
        self.groupBoxAxisStepMove = QtWidgets.QGroupBox(self.tab)
        self.groupBoxAxisStepMove.setGeometry(QtCore.QRect(500, 200, 341, 141))
        self.groupBoxAxisStepMove.setObjectName("groupBoxAxisStepMove")
        self.label_12 = QtWidgets.QLabel(self.groupBoxAxisStepMove)
        self.label_12.setGeometry(QtCore.QRect(10, 30, 67, 17))
        self.label_12.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_12.setObjectName("label_12")
        self.label_15 = QtWidgets.QLabel(self.groupBoxAxisStepMove)
        self.label_15.setGeometry(QtCore.QRect(10, 70, 67, 17))
        self.label_15.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBoxAxisStepMove)
        self.label_16.setGeometry(QtCore.QRect(10, 110, 67, 17))
        self.label_16.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_16.setObjectName("label_16")
        self.pushButtonStepMoveZ = QtWidgets.QPushButton(self.groupBoxAxisStepMove)
        self.pushButtonStepMoveZ.setGeometry(QtCore.QRect(230, 109, 75, 19))
        self.pushButtonStepMoveZ.setObjectName("pushButtonStepMoveZ")
        self.textEditStepMoveX = QtWidgets.QTextEdit(self.groupBoxAxisStepMove)
        self.textEditStepMoveX.setGeometry(QtCore.QRect(110, 24, 91, 31))
        self.textEditStepMoveX.setObjectName("textEditStepMoveX")
        self.textEditStepMoveZ = QtWidgets.QTextEdit(self.groupBoxAxisStepMove)
        self.textEditStepMoveZ.setGeometry(QtCore.QRect(110, 104, 91, 31))
        self.textEditStepMoveZ.setObjectName("textEditStepMoveZ")
        self.pushButtonStepMoveY = QtWidgets.QPushButton(self.groupBoxAxisStepMove)
        self.pushButtonStepMoveY.setGeometry(QtCore.QRect(230, 69, 75, 20))
        self.pushButtonStepMoveY.setObjectName("pushButtonStepMoveY")
        self.pushButtonStepMoveX = QtWidgets.QPushButton(self.groupBoxAxisStepMove)
        self.pushButtonStepMoveX.setGeometry(QtCore.QRect(230, 29, 75, 19))
        self.pushButtonStepMoveX.setObjectName("pushButtonStepMoveX")
        self.textEditStepMoveY = QtWidgets.QTextEdit(self.groupBoxAxisStepMove)
        self.textEditStepMoveY.setGeometry(QtCore.QRect(110, 64, 91, 31))
        self.textEditStepMoveY.setObjectName("textEditStepMoveY")
        self.pushButtonSignalReSet = QtWidgets.QPushButton(self.tab)
        self.pushButtonSignalReSet.setGeometry(QtCore.QRect(220, 10, 111, 23))
        self.pushButtonSignalReSet.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButtonSignalReSet.setObjectName("pushButtonSignalReSet")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 340, 211, 121))
        self.groupBox.setObjectName("groupBox")
        self.radioButtonUSB2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButtonUSB2.setGeometry(QtCore.QRect(80, 30, 61, 20))
        self.radioButtonUSB2.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.radioButtonUSB2.setObjectName("radioButtonUSB2")
        self.radioButtonUSB1 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButtonUSB1.setGeometry(QtCore.QRect(10, 30, 61, 20))
        self.radioButtonUSB1.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.radioButtonUSB1.setObjectName("radioButtonUSB1")
        self.radioButtonUSBall = QtWidgets.QRadioButton(self.groupBox)
        self.radioButtonUSBall.setGeometry(QtCore.QRect(150, 30, 51, 20))
        self.radioButtonUSBall.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.radioButtonUSBall.setObjectName("radioButtonUSBall")
        self.pushButtonEnableUSB = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonEnableUSB.setGeometry(QtCore.QRect(20, 90, 75, 19))
        self.pushButtonEnableUSB.setObjectName("pushButtonEnableUSB")
        self.pushButtonDisableUSB = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonDisableUSB.setGeometry(QtCore.QRect(120, 90, 75, 19))
        self.pushButtonDisableUSB.setObjectName("pushButtonDisableUSB")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(264, 340, 211, 121))
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButtonDUT2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButtonDUT2.setGeometry(QtCore.QRect(80, 30, 61, 20))
        self.radioButtonDUT2.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.radioButtonDUT2.setObjectName("radioButtonDUT2")
        self.radioButtonDUT1 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButtonDUT1.setGeometry(QtCore.QRect(10, 30, 61, 20))
        self.radioButtonDUT1.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.radioButtonDUT1.setObjectName("radioButtonDUT1")
        self.radioButtonDUTall = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButtonDUTall.setGeometry(QtCore.QRect(150, 30, 51, 20))
        self.radioButtonDUTall.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.radioButtonDUTall.setObjectName("radioButtonDUTall")
        self.pushButtonLockDUT = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtonLockDUT.setGeometry(QtCore.QRect(20, 90, 75, 19))
        self.pushButtonLockDUT.setObjectName("pushButtonLockDUT")
        self.pushButtonUnlockDUT = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtonUnlockDUT.setGeometry(QtCore.QRect(120, 90, 75, 19))
        self.pushButtonUnlockDUT.setObjectName("pushButtonUnlockDUT")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(500, 340, 251, 121))
        self.groupBox_3.setObjectName("groupBox_3")
        self.radioButtonPower2 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButtonPower2.setGeometry(QtCore.QRect(100, 30, 71, 20))
        self.radioButtonPower2.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.radioButtonPower2.setObjectName("radioButtonPower2")
        self.radioButtonPower1 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButtonPower1.setGeometry(QtCore.QRect(20, 30, 71, 20))
        self.radioButtonPower1.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.radioButtonPower1.setObjectName("radioButtonPower1")
        self.radioButtonPowerall = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButtonPowerall.setGeometry(QtCore.QRect(180, 30, 51, 20))
        self.radioButtonPowerall.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.radioButtonPowerall.setObjectName("radioButtonPowerall")
        self.pushButtonEnablePower = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButtonEnablePower.setGeometry(QtCore.QRect(20, 90, 101, 19))
        self.pushButtonEnablePower.setObjectName("pushButtonEnablePower")
        self.pushButtonDisablePower = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButtonDisablePower.setGeometry(QtCore.QRect(140, 90, 101, 19))
        self.pushButtonDisablePower.setObjectName("pushButtonDisablePower")
        self.pushButtonGetPLCVer = QtWidgets.QPushButton(self.tab)
        self.pushButtonGetPLCVer.setGeometry(QtCore.QRect(380, 10, 111, 23))
        self.pushButtonGetPLCVer.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButtonGetPLCVer.setObjectName("pushButtonGetPLCVer")
        self.textEditPLCVer = QtWidgets.QTextEdit(self.tab)
        self.textEditPLCVer.setGeometry(QtCore.QRect(510, 10, 104, 21))
        self.textEditPLCVer.setObjectName("textEditPLCVer")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(780, 340, 251, 121))
        self.groupBox_4.setObjectName("groupBox_4")
        self.radioButtonDUT2Sensor = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButtonDUT2Sensor.setGeometry(QtCore.QRect(150, 30, 81, 20))
        self.radioButtonDUT2Sensor.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.radioButtonDUT2Sensor.setObjectName("radioButtonDUT2Sensor")
        self.radioButtonDUT1Sensor = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButtonDUT1Sensor.setGeometry(QtCore.QRect(20, 30, 81, 20))
        self.radioButtonDUT1Sensor.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.radioButtonDUT1Sensor.setObjectName("radioButtonDUT1Sensor")
        self.pushButtonSensorOFF = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButtonSensorOFF.setGeometry(QtCore.QRect(20, 90, 101, 19))
        self.pushButtonSensorOFF.setObjectName("pushButtonSensorOFF")
        self.pushButtonSensorON = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButtonSensorON.setGeometry(QtCore.QRect(140, 90, 101, 19))
        self.pushButtonSensorON.setObjectName("pushButtonSensorON")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton_44 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_44.setGeometry(QtCore.QRect(100, 60, 221, 281))
        self.pushButton_44.setStyleSheet("background-color: rgb(33, 255, 239);")
        self.pushButton_44.setObjectName("pushButton_44")
        self.ButtonSetXCalUp = QtWidgets.QPushButton(self.tab_2)
        self.ButtonSetXCalUp.setGeometry(QtCore.QRect(170, 10, 61, 32))
        self.ButtonSetXCalUp.setStyleSheet("background-color: rgb(255, 222, 29);")
        self.ButtonSetXCalUp.setObjectName("ButtonSetXCalUp")
        self.ButtonSetZCal = QtWidgets.QPushButton(self.tab_2)
        self.ButtonSetZCal.setGeometry(QtCore.QRect(150, 250, 111, 32))
        self.ButtonSetZCal.setStyleSheet("background-color: rgb(255, 222, 29);")
        self.ButtonSetZCal.setObjectName("ButtonSetZCal")
        self.ButtonSetXCalDown = QtWidgets.QPushButton(self.tab_2)
        self.ButtonSetXCalDown.setGeometry(QtCore.QRect(180, 370, 61, 32))
        self.ButtonSetXCalDown.setStyleSheet("background-color: rgb(255, 222, 29);")
        self.ButtonSetXCalDown.setObjectName("ButtonSetXCalDown")
        self.ButtonSetYCalLeft = QtWidgets.QPushButton(self.tab_2)
        self.ButtonSetYCalLeft.setGeometry(QtCore.QRect(20, 170, 61, 32))
        self.ButtonSetYCalLeft.setStyleSheet("background-color: rgb(255, 222, 29);")
        self.ButtonSetYCalLeft.setObjectName("ButtonSetYCalLeft")
        self.ButtonSetYCalRight = QtWidgets.QPushButton(self.tab_2)
        self.ButtonSetYCalRight.setGeometry(QtCore.QRect(340, 170, 61, 32))
        self.ButtonSetYCalRight.setStyleSheet("background-color: rgb(255, 222, 29);")
        self.ButtonSetYCalRight.setObjectName("ButtonSetYCalRight")
        self.ButtonCylinderOut = QtWidgets.QPushButton(self.tab_2)
        self.ButtonCylinderOut.setGeometry(QtCore.QRect(460, 240, 121, 32))
        self.ButtonCylinderOut.setStyleSheet("background-color: rgb(255, 222, 29);")
        self.ButtonCylinderOut.setObjectName("ButtonCylinderOut")
        self.ButtonCylinderIn = QtWidgets.QPushButton(self.tab_2)
        self.ButtonCylinderIn.setGeometry(QtCore.QRect(460, 290, 121, 32))
        self.ButtonCylinderIn.setStyleSheet("background-color: rgb(255, 222, 29);")
        self.ButtonCylinderIn.setObjectName("ButtonCylinderIn")
        self.label_38 = QtWidgets.QLabel(self.tab_2)
        self.label_38.setGeometry(QtCore.QRect(670, 170, 71, 41))
        self.label_38.setStyleSheet("background-color: rgb(22, 160, 255);")
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.textEditOffset = QtWidgets.QTextEdit(self.tab_2)
        self.textEditOffset.setGeometry(QtCore.QRect(750, 170, 121, 41))
        self.textEditOffset.setObjectName("textEditOffset")
        self.ButtonStartCal = QtWidgets.QPushButton(self.tab_2)
        self.ButtonStartCal.setGeometry(QtCore.QRect(460, 170, 121, 51))
        self.ButtonStartCal.setStyleSheet("background-color: rgb(41, 255, 229);")
        self.ButtonStartCal.setObjectName("ButtonStartCal")
        self.ButtonCurtainOFF = QtWidgets.QPushButton(self.tab_2)
        self.ButtonCurtainOFF.setGeometry(QtCore.QRect(670, 290, 121, 32))
        self.ButtonCurtainOFF.setStyleSheet("background-color: rgb(255, 222, 29);")
        self.ButtonCurtainOFF.setObjectName("ButtonCurtainOFF")
        self.ButtonCurtainON = QtWidgets.QPushButton(self.tab_2)
        self.ButtonCurtainON.setGeometry(QtCore.QRect(670, 240, 121, 32))
        self.ButtonCurtainON.setStyleSheet("background-color: rgb(255, 222, 29);")
        self.ButtonCurtainON.setObjectName("ButtonCurtainON")
        self.ButtonBurninStart = QtWidgets.QPushButton(self.tab_2)
        self.ButtonBurninStart.setGeometry(QtCore.QRect(860, 240, 121, 32))
        self.ButtonBurninStart.setStyleSheet("background-color: rgb(255, 222, 29);")
        self.ButtonBurninStart.setObjectName("ButtonBurninStart")
        self.textEditBurninTimes = QtWidgets.QTextEdit(self.tab_2)
        self.textEditBurninTimes.setGeometry(QtCore.QRect(860, 290, 121, 31))
        self.textEditBurninTimes.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEditBurninTimes.setObjectName("textEditBurninTimes")
        self.ButtonRunPattern = QtWidgets.QPushButton(self.tab_2)
        self.ButtonRunPattern.setGeometry(QtCore.QRect(670, 350, 121, 32))
        self.ButtonRunPattern.setStyleSheet("background-color: rgb(255, 222, 29);")
        self.ButtonRunPattern.setObjectName("ButtonRunPattern")
        self.comboBox = QtWidgets.QComboBox(self.tab_2)
        self.comboBox.setGeometry(QtCore.QRect(670, 400, 121, 31))
        self.comboBox.setStyleSheet("background-color: rgb(22, 160, 255);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.ButtonLEDControl = QtWidgets.QPushButton(self.tab_2)
        self.ButtonLEDControl.setGeometry(QtCore.QRect(460, 350, 121, 32))
        self.ButtonLEDControl.setStyleSheet("background-color: rgb(255, 222, 29);")
        self.ButtonLEDControl.setObjectName("ButtonLEDControl")
        self.comboBoxLED = QtWidgets.QComboBox(self.tab_2)
        self.comboBoxLED.setGeometry(QtCore.QRect(460, 400, 121, 31))
        self.comboBoxLED.setStyleSheet("background-color: rgb(22, 160, 255);")
        self.comboBoxLED.setObjectName("comboBoxLED")
        self.comboBoxLED.addItem("")
        self.comboBoxLED.addItem("")
        self.comboBoxLED.addItem("")
        self.comboBoxLED.addItem("")
        self.comboBoxLED.addItem("")
        self.comboBoxLED.addItem("")
        self.comboBoxLED.addItem("")
        self.comboBoxLED.addItem("")
        self.comboBoxLED.addItem("")
        self.comboBoxLED.addItem("")
        self.comboBoxLED.addItem("")
        self.comboBoxLED.addItem("")
        self.tabWidget.addTab(self.tab_2, "")
        self.label_bottom = QtWidgets.QLabel(Form)
        self.label_bottom.setGeometry(QtCore.QRect(10, 540, 1071, 20))
        self.label_bottom.setStyleSheet("background-color: rgb(34, 194, 255);")
        self.label_bottom.setAlignment(QtCore.Qt.AlignCenter)
        self.label_bottom.setObjectName("label_bottom")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "BojayE71Touch"))
        self.label_top.setText(_translate("Form", "Bojay E71Touch UI V1.0"))
        self.pushButtonOpenPort.setText(_translate("Form", "OpenPort"))
        self.pushButtonClosePort.setText(_translate("Form", "ClosePort"))
        self.checkBoxPLC.setText(_translate("Form", "PLC"))
        self.groupBoxAxisSpeed.setTitle(_translate("Form", "Axis Speed"))
        self.label_5.setText(_translate("Form", "Z Axis"))
        self.pushButtonSpeedSet.setText(_translate("Form", "Set"))
        self.label_3.setText(_translate("Form", "Y Axis"))
        self.pushButtonSpeedGet.setText(_translate("Form", "Get"))
        self.label.setText(_translate("Form", "X Axis"))
        self.groupBoxAxisLimit.setTitle(_translate("Form", "Axis Limit"))
        self.pushButtonLimitGet.setText(_translate("Form", "Get"))
        self.pushButtonLimitSet.setText(_translate("Form", "Set"))
        self.label_2.setText(_translate("Form", "X Axis"))
        self.label_8.setText(_translate("Form", "Z Axis"))
        self.label_4.setText(_translate("Form", "Y Axis"))
        self.label_maxlimit.setText(_translate("Form", "MaxLimit"))
        self.label_minlimit.setText(_translate("Form", "MinLimit"))
        self.pushButtonPassword.setText(_translate("Form", "Password"))
        self.groupBoxMoveCoordiante.setTitle(_translate("Form", "Move Coordinate"))
        self.pushButtonMovex.setText(_translate("Form", "Move X"))
        self.pushButtonMovey.setText(_translate("Form", "Move Y"))
        self.pushButtonMovez.setText(_translate("Form", "Move Z"))
        self.pushButtonGetx.setText(_translate("Form", "Get X"))
        self.pushButtonGety.setText(_translate("Form", "Get Y"))
        self.pushButtonGetz.setText(_translate("Form", "Get Z"))
        self.label_10.setText(_translate("Form", "X Axis"))
        self.label_11.setText(_translate("Form", "Z Axis"))
        self.label_14.setText(_translate("Form", "Y Axis"))
        self.groupBoxAxisStepMove.setTitle(_translate("Form", "Set step"))
        self.label_12.setText(_translate("Form", "X Axis"))
        self.label_15.setText(_translate("Form", "Y Axis"))
        self.label_16.setText(_translate("Form", "Z Axis"))
        self.pushButtonStepMoveZ.setText(_translate("Form", "Move Z"))
        self.pushButtonStepMoveY.setText(_translate("Form", "Move Y"))
        self.pushButtonStepMoveX.setText(_translate("Form", "Move X"))
        self.pushButtonSignalReSet.setText(_translate("Form", "SignalReSet"))
        self.groupBox.setTitle(_translate("Form", "USB"))
        self.radioButtonUSB2.setText(_translate("Form", "USB2"))
        self.radioButtonUSB1.setText(_translate("Form", "USB1"))
        self.radioButtonUSBall.setText(_translate("Form", "All"))
        self.pushButtonEnableUSB.setText(_translate("Form", "EnableUSB"))
        self.pushButtonDisableUSB.setText(_translate("Form", "DisabelUSB"))
        self.groupBox_2.setTitle(_translate("Form", "DUT"))
        self.radioButtonDUT2.setText(_translate("Form", "DUT2"))
        self.radioButtonDUT1.setText(_translate("Form", "DUT1"))
        self.radioButtonDUTall.setText(_translate("Form", "All"))
        self.pushButtonLockDUT.setText(_translate("Form", "LockDUT"))
        self.pushButtonUnlockDUT.setText(_translate("Form", "UnlockDUT"))
        self.groupBox_3.setTitle(_translate("Form", "Power"))
        self.radioButtonPower2.setText(_translate("Form", "Power2"))
        self.radioButtonPower1.setText(_translate("Form", "Power1"))
        self.radioButtonPowerall.setText(_translate("Form", "All"))
        self.pushButtonEnablePower.setText(_translate("Form", "EnablePower"))
        self.pushButtonDisablePower.setText(_translate("Form", "DisablePower"))
        self.pushButtonGetPLCVer.setText(_translate("Form", "ReadPCLVer"))
        self.groupBox_4.setTitle(_translate("Form", "DUTSensor"))
        self.radioButtonDUT2Sensor.setText(_translate("Form", "Sensor2"))
        self.radioButtonDUT1Sensor.setText(_translate("Form", "Sensor1"))
        self.pushButtonSensorOFF.setText(_translate("Form", "SensorOFF"))
        self.pushButtonSensorON.setText(_translate("Form", "SensorON"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "PLC"))
        self.pushButton_44.setText(_translate("Form", "I am calibration KIT"))
        self.ButtonSetXCalUp.setText(_translate("Form", "Set Up"))
        self.ButtonSetZCal.setText(_translate("Form", "Set Z "))
        self.ButtonSetXCalDown.setText(_translate("Form", "Set down"))
        self.ButtonSetYCalLeft.setText(_translate("Form", "Set Left"))
        self.ButtonSetYCalRight.setText(_translate("Form", "Set Right"))
        self.ButtonCylinderOut.setText(_translate("Form", "Cylinder out"))
        self.ButtonCylinderIn.setText(_translate("Form", "Cylinder in"))
        self.label_38.setText(_translate("Form", "Offset"))
        self.ButtonStartCal.setText(_translate("Form", "Start Cal"))
        self.ButtonCurtainOFF.setText(_translate("Form", "LightCurtainOFF"))
        self.ButtonCurtainON.setText(_translate("Form", "LightCurtainON"))
        self.ButtonBurninStart.setText(_translate("Form", "BurninStart"))
        self.ButtonRunPattern.setText(_translate("Form", "RunPattern"))
        self.comboBox.setItemText(0, _translate("Form", "Rectangle"))
        self.comboBox.setItemText(1, _translate("Form", "Circle/EIIipse"))
        self.ButtonLEDControl.setText(_translate("Form", "LEDControl"))
        self.comboBoxLED.setItemText(0, _translate("Form", "1-red-on"))
        self.comboBoxLED.setItemText(1, _translate("Form", "1-red-off"))
        self.comboBoxLED.setItemText(2, _translate("Form", "1-yellow-on"))
        self.comboBoxLED.setItemText(3, _translate("Form", "1-yellow-off"))
        self.comboBoxLED.setItemText(4, _translate("Form", "1-green-on"))
        self.comboBoxLED.setItemText(5, _translate("Form", "1-green-off"))
        self.comboBoxLED.setItemText(6, _translate("Form", "2-red-on"))
        self.comboBoxLED.setItemText(7, _translate("Form", "2-red-off"))
        self.comboBoxLED.setItemText(8, _translate("Form", "2-green-on"))
        self.comboBoxLED.setItemText(9, _translate("Form", "2-green-off"))
        self.comboBoxLED.setItemText(10, _translate("Form", "2-yellow-on"))
        self.comboBoxLED.setItemText(11, _translate("Form", "2-yellow-off"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Cal"))
        self.label_bottom.setText(_translate("Form", "Developed by Bojay"))

